WebApp.App/Controllers/CashiersController.cs
namespace WebApp.App.Controllers
{
    public class CashiersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CashiersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            CashierViewModel = new CashierViewModel();
        }

        [BindProperty]
        public CashierViewModel CashierViewModel { get; set; }

        public IActionResult Index()
        {
            CashierViewModel.Cashiers = _unitOfWork.CashierService.GetAll().ToList();

            if (CashierViewModel.Cashiers == null)
                return NotFound("no data found");

            return View(CashierViewModel);
        }

        public IActionResult Add()
        {
            LoadSelectListItems();

            return View(CashierViewModel);
        }

        [HttpPost]
        [ActionName(name: "Add")]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitAdd()
        {
            if (!ModelState.IsValid)
            {
                LoadSelectListItems();

                return View(CashierViewModel);
            }

            _unitOfWork.CashierService.Add(CashierViewModel.Cashier);
            _unitOfWork.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            CashierViewModel.Cashier = _unitOfWork.CashierService.FindObject(x => x.Id == id);

            LoadSelectListItems();

            if (CashierViewModel.Cashier == null)
                return NotFound("no data found");

            return View(CashierViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update()
        {
            if (!ModelState.IsValid)
            {
                LoadSelectListItems();

                return View(CashierViewModel);
            }

            _unitOfWork.CashierService.Update(CashierViewModel.Cashier);
            _unitOfWork.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            try
            {
                CashierViewModel.Cashier = _unitOfWork.CashierService.FindObject(x => x.Id == id);
                if (CashierViewModel.Cashier == null)
                    return NotFound("no data found");

                _unitOfWork.CashierService.Remove(CashierViewModel.Cashier);
                _unitOfWork.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return BadRequest("can't delete this item since it's in use");
            }
        }

        public void LoadSelectListItems()
        {
            CashierViewModel.ListItems = _unitOfWork.BranchSrvice.GetAll()
                .Select(branch => new SelectListItem
                {
                    Text = branch.BranchName,
                    Value = branch.Id.ToString(),
                    Selected = CashierViewModel.Cashier != null && CashierViewModel.Cashier.BranchId == branch.Id
                }).ToList();
        }
    }
}

WebApp.App/Controllers/CitiesController.cs
namespace WebApp.App.Controllers
{
    public class CitiesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CitiesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var cities = _unitOfWork.CityService.GetAll().ToList();
            if (cities == null)
                return NotFound("no data found");

            return View(cities);
        }

        public IActionResult Add()
        {
            City city = new();
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(City city)
        {
            if (!ModelState.IsValid)
                return View(city);

            _unitOfWork.CityService.Add(city);
            _unitOfWork.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            City city = _unitOfWork.CityService.FindObject(x => x.Id == id);
            if (city == null)
                return NotFound("no data found");

            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(City city)
        {
            if (!ModelState.IsValid)
                return View(city);

            _unitOfWork.CityService.Update(city);
            _unitOfWork.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            try
            {
                City city = _unitOfWork.CityService.FindObject(x => x.Id == id);
                if (city == null)
                    return NotFound("no data found");

                _unitOfWork.CityService.Remove(city);
                _unitOfWork.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return BadRequest("can't delete this item since it's in use");
            }
        }
    }
}

WebApp.App/Controllers/InvoiceDetailsController.cs
namespace WebApp.App.Controllers
{
    public class InvoiceDetailsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public InvoiceDetailsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var invoiceDetails = _unitOfWork.InvoiceDetailService.GetAll().ToList();
            if (invoiceDetails == null)
                return NotFound("no data found");

            return View(invoiceDetails);
        }

        public IActionResult Add(int invoiceHeaderId)
        {
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            InvoiceDetail invoiceDetail = new()
            {
                InvoiceHeaderId = invoiceHeaderId,
            };

            return View("Add_Update", invoiceDetail);
        }

        [HttpPost]
        [ActionName(name: "Add")]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitAdd(InvoiceDetail invoiceDetail, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View("Add_Update", invoiceDetail);
            }

            _unitOfWork.InvoiceDetailService.Add(invoiceDetail);
            _unitOfWork.SaveChanges();
            return Redirect(returnUrl);
        }

        public IActionResult Update(int id)
        {
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            InvoiceDetail invoiceDetail = _unitOfWork.InvoiceDetailService.FindObject(x => x.Id == id);

            if (invoiceDetail == null)
                return NotFound("no data found");

            return View("Add_Update", invoiceDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(InvoiceDetail invoiceDetail, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View("Add_Update", invoiceDetail);
            }

            _unitOfWork.InvoiceDetailService.Update(invoiceDetail);
            _unitOfWork.SaveChanges();
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int invoiceDetailId, int invoiceHeaderId)
        {
            try
            {
                InvoiceDetail invoiceDetail = _unitOfWork.InvoiceDetailService.FindObject(x => x.Id == invoiceDetailId);
                if (invoiceDetail == null)
                    return NotFound("no data found");

                _unitOfWork.InvoiceDetailService.Remove(invoiceDetail);
                _unitOfWork.SaveChanges();
                return RedirectToAction(actionName: "Details", controllerName: "InvoiceHeaders", routeValues: new { id = invoiceHeaderId });
            }
            catch
            {
                return BadRequest("can't delete this item since it's in use");
            }
        }

    }
}

WebApp.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp.App</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- IconsKD -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <!-- data table -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NavBar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <!-- data table -->
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp.App/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp.App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @*                <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>*@
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="branches" asp-action="Index">Branches</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Cashiers" asp-action="Index">Cashiers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="InvoiceHeaders" asp-action="Index">Invoice Headers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="InvoiceDetails" asp-action="Index">Invoice Details</a>
                </li>
            </ul>
        </div>
    </div>
</nav>